name: "[Action] Semantic Release"
description: "Automate versioning & changelog for Rust crates and/or JS packages via semantic‑release"

inputs:
  release-type:
    description: "Explicit release level override (major | minor | patch)"
    required: false

outputs:
  version:
    description: "The new version number"
    value: ${{ steps.set-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0         # semantic-release needs the full history

    - id: detect
      shell: bash
      run: |
        if [[ -f Cargo.toml ]];     then echo "is_rust=true" >>"$GITHUB_OUTPUT"; fi
        if [[ -f package.json ]];   then echo "is_node=true" >>"$GITHUB_OUTPUT"; fi

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        # Only enable the npm cache when we actually have a lock-file
        cache: ${{ steps.detect.outputs.is_node == 'true' && 'npm' || '' }}

    - name: Install npm dependencies
      if: steps.detect.outputs.is_node == 'true'
      shell: bash
      run: npm ci --ignore-scripts

    - name: Build (npm)
      if: steps.detect.outputs.is_node == 'true'
      shell: bash
      run: npm run build --if-present

    - name: Install build essentials
      if: steps.detect.outputs.is_rust == 'true'
      shell: bash
      run: |
        if command -v apt-get &>/dev/null; then
          sudo apt-get update -yq
          sudo apt-get install -y --no-install-recommends \
            build-essential pkg-config libssl-dev ca-certificates
        elif command -v apk &>/dev/null; then
          sudo apk add --no-cache build-base pkgconf openssl-dev
        fi

    - name: Set up Rust
      if: steps.detect.outputs.is_rust == 'true'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install cargo-release & git-cliff
      if: steps.detect.outputs.is_rust == 'true'
      uses: cargo-bins/cargo-binstall@v1.12.7
      with:
        binary: "cargo-release git-cliff"

    - name: Set semantic-release config file
      id: set-config
      shell: bash
      run: |
        if [[ -n "${{ inputs.release-type }}" ]]; then
          echo "release_config=--extends=./.releaserc.${{ inputs.release-type }}.json" >> $GITHUB_OUTPUT
        else
          echo "release_config=" >> $GITHUB_OUTPUT
        fi

    - name: Install semantic-release & plugins
      shell: bash
      run: |
        npm install --no-save \
          semantic-release \
          @semantic-release/changelog \
          @semantic-release/commit-analyzer \
          @semantic-release/exec \
          @semantic-release/git \
          @semantic-release/github \
          @semantic-release/release-notes-generator \
          semantic-release-cargo \
          semantic-release-github-actions-tags \
          semantic-release-helm3

    - name: Run semantic-release
      id: semantic-release
      shell: bash
      env:
        GITHUB_OUTPUT: $GITHUB_OUTPUT
        CARGO_REGISTRY_TOKEN: ${{ env.CARGO_REGISTRY_TOKEN }}
      run: |
        npx semantic-release ${{ steps.set-config.outputs.release_config }}

    - id: set-version
      if: always()
      shell: bash
      run: echo "version=${{ steps.semantic-release.outputs.nextRelease.version }}" >> "$GITHUB_OUTPUT"
