name: 'Build and Push Docker Image'
description: 'Builds and Pushes a docker image'

inputs:
  release-type:
    description: 'The type of release'
    required: false
    type: string

outputs:
  version:
    description: 'The new version number'
    value: ${{ steps.semantic-release.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # semantic-release requires all commits/tags

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: use specific releaserc file
      shell: bash
      if: ${{ inputs.release-type }}
      run: |
        echo "RELEASE_TYPE=--config .releaserc.${{ inputs.release-type }}.json" >> $GITHUB_ENV

    - name: Run semantic-release
      shell: bash
      id: semantic-release
      run: |
        echo $RELEASE_TYPE
        
        npx -p semantic-release \
          -p @semantic-release/commit-analyzer \
          -p @semantic-release/release-notes-generator \
          -p @semantic-release/git \
          -p @semantic-release/github \
          -p @semantic-release/changelog \
          -p @semantic-release/exec \
          semantic-release $RELEASE_TYPE
