name: '[Action] Semantic Release'
description: 'Use semantic-release to automate versioning and releases'

inputs:
  release-type:
    description: 'The type of release'
    required: false

outputs:
  version:
    description: 'The new version number'
    value: ${{ steps.semantic-release.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # semantic-release requires all commits/tags

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      shell: bash
      run: npm ci || true

    - name: Build
      shell: bash
      run: npm run build || true

    - name: Set semantic-release config file
      id: set-config
      shell: bash
      run: |
        if [[ -n "${{ inputs.release-type }}" ]]; then
          echo "release_config=--extends=./.releaserc.${{ inputs.release-type }}.json" >> $GITHUB_OUTPUT
        else
          echo "release_config=" >> $GITHUB_OUTPUT
        fi

    - name: Run semantic-release
      shell: bash
      id: semantic-release
      env:
        GITHUB_OUTPUT: $GITHUB_OUTPUT
      run: |
        npm install --no-save \
          semantic-release \
          @semantic-release/changelog \
          @semantic-release/commit-analyzer \
          @semantic-release/exec \
          @semantic-release/git \
          @semantic-release/github \
          semantic-release-helm3 \
          @semantic-release/release-notes-generator \
          semantic-release-github-actions-tags

        npx semantic-release ${{ steps.set-config.outputs.release_config }}
