name: 'Build'

on:
  workflow_call:

jobs:
  composer-install:
    name: 'Composer install'
    runs-on: [self-hosted, dind]
    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: webgrip/workflows/.github/php/8.2/actions/composer-install@main

  composer-install-on-container:
    name: 'Composer install'
    runs-on: [self-hosted, dind]
    environment: production
    container:
      image: composer:2.8.5
    steps:
      - uses: actions/checkout@v4
      - name: 'Install dependencies'
        run: composer install --prefer-dist --no-interaction