name: 'Build'

on:
  workflow_call:
    secrets:
      COMPOSER_TOKEN:
        description: 'Composer packagist token. Required to authenticate with for example private packagist. (packagist.com)'
        required: false

jobs:
  composer-install:
    name: 'Composer install'
    runs-on: arc-runner-set
    steps:
      - run: |
          pwd

      - run: |
          ls -la

      - uses: actions/checkout@v4

      - run: |
          ls -la

      - uses: actions/cache@v4
        with:
          path: vendor
          key: "composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}"

      - run: |
          ls -la
          ls -la vendor || true

      - uses: webgrip/workflows/.github/php/8.2/actions/composer-install@main
        with:
          composer_auth: >
            {
              "http-basic": {
                "repo.packagist.com": {
                  "username": "token",
                  "password": "${{ secrets.COMPOSER_TOKEN }}"
                }
              }
            }


  composer-install-on-container:
    name: 'Composer install on container'
    runs-on: arc-runner-set
    container:
      image: composer:2.8.5
    steps:
      - run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - run: ls -la
      - uses: actions/checkout@v4
      - run: ls -la
      - name: 'Install dependencies'
        run: composer install --prefer-dist --no-interaction --ignore-platform-reqs
      - run: | 
          ls -la
          ls -la vendor || true

  php-test:
    name: 'PHP test'
    runs-on: arc-runner-set
    container:
      image: php:8.2-cli
    steps:
      - uses: actions/checkout@v4
      - name: echo version
        shell: bash
        run: |
          echo "PHP Version: $(php -v)"
