on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        description: >-
          DockerHub username (optional, for pushing to Docker Hub
          in addition to GHCR)
        required: false
      DOCKER_TOKEN:
        description: >-
          DockerHub token (optional, for pushing to Docker Hub
          in addition to GHCR)
        required: false
    inputs:
      docker-context:
        type: string
        description: 'Docker context'
        required: true
        default: '.'
      docker-file:
        type: string
        description: 'Dockerfile path from the context'
        required: true
        default: 'Dockerfile'
      docker-tags:
        type: string
        description: 'Docker tags'
        required: true
      docker-target:
        type: string
        description: 'Docker target'
        required: false
        default: ''

run-name: ${{ inputs.docker-context }}/${{ inputs.docker-file }}

jobs:
  build:
    name: "Docker Build and Push"
    runs-on: arc-runner-set
    permissions:
      contents: read
      packages: write
    steps:
      - uses: webgrip/workflows/.github/composite-actions/docker-build-push@main
        with:
          docker-context: ${{ inputs.docker-context }}
          docker-file: ${{ inputs.docker-file }}
          docker-tags: ${{ inputs.docker-tags }}
          docker-target: ${{ inputs.docker-target }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
