on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
          description: 'DockerHub username'
          required: true
      DOCKER_TOKEN:
          description: 'DockerHub token'
          required: true
    inputs:
      docker-context:
        type: string
        description: 'Docker context'
        required: true
        default: '.'
      docker-file:
        type: string
        description: 'Dockerfile path from the context'
        required: true
        default: 'Dockerfile'
      docker-tags:
        type: string
        description: 'Docker tags'
        required: true

run-name: ${{ inputs.docker-context }}/${{ inputs.docker-file }}

jobs:
  build:
    name: "Build Docker Image"
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: ls -la ${{ inputs.docker-context }}
      - uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.docker-context }}/${{ inputs.docker-file }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ inputs.docker-tags }}
