name: '[Call] Run Linting'

on:
  workflow_call:

jobs:
  eslint:
    name: 'ESLint'
    runs-on: arc-runner-set
    container: node:22

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint