on:
  workflow_call:
    secrets:
      WEBGRIP_CI_CLIENT_ID:
        description: "GitHub App ID (numeric)"
        required: true
      WEBGRIP_CI_APP_PRIVATE_KEY:
        description: "GitHub App private key (PEM)"
        required: true
    inputs:
      prompt-repository:
        type: string
        description: 'The repository in which the prompt.yml files are located'
        required: true
        default: 'webgrip/agentic-workflows'
      prompt-paths:
        type: string
        description: 'Comma-separated list of prompt file paths (relative to prompt-repository root)'
        required: true
      target-repository:
        type: string
        description: 'The repository in which to create the issue'
        required: true

jobs:
  issues-from-prompts:
    name: "Create issues from prompt files (matrix)"
    strategy:
      fail-fast: false
      matrix:
        prompt-path: ${{ fromJson(inputs.prompt-paths) }}
    uses: webgrip/workflows/.github/workflows/github-issue-create-by-prompt.yml@main
    with:
      prompt-repository: ${{ inputs.prompt-repository }}
      prompt-path: ${{ matrix.prompt-path }}
      issue-title: ${{ matrix.prompt-path }}
      target-repository: ${{ inputs.target-repository }}
    secrets:
      WEBGRIP_CI_CLIENT_ID: ${{ secrets.WEBGRIP_CI_CLIENT_ID }}
      WEBGRIP_CI_APP_PRIVATE_KEY: ${{ secrets.WEBGRIP_CI_APP_PRIVATE_KEY }}
