name: '[Call] Push Helm Chart'

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to the Helm chart you wish to validate'
        type: string
        required: true
      name:
        description: 'Name of the Helm chart'
        type: string
        required: true
      version:
        description: 'Version of the Helm chart'
        type: string
        required: true

jobs:
  helm-chart-push:
    name: 'Push Helm Chart'
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
      # validate again?
      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username $GITHUB_ACTOR --password-stdin
      - run: |
          export HELM_EXPERIMENTAL_OCI=1
      - run: |
          cd ${{ inputs.path }}
          helm package . ghcr.io/${{ github.repository }}/${{inputs.name}}:${{ inputs.version }}
          helm push ghcr.io/${{ github.repository }}/${{inputs.name}}:${{ inputs.version }}

