name: '[Call] Validate Helm Chart'

on:
  workflow_call:
    inputs:
      paths:
        description: 'A matrix of paths to Helm charts to validate'
        type: string
        required: true

jobs:
  helm-charts-validate:
    name: 'Validate Helm Charts'
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.paths) }}
    uses: webgrip/workflows/.github/workflows/helm-chart-validate.yml@ubuntu-latest
    with:
      path: ${{ matrix.path }}
