name: '[Call] Push Helm Chart'

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to the Helm chart you wish to validate'
        type: string
        required: true
      name:
        description: 'Name of the Helm chart'
        type: string
        required: true
      version:
        description: 'Version of the Helm chart'
        type: string
        required: true

jobs:
  helm-chart-push:
    name: 'Push Helm Chart'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }} # Make sure we are on the tagged versioned commit
      - uses: azure/setup-helm@v4
      # validate again?
      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username $GITHUB_ACTOR --password-stdin
      - run: |
          export HELM_EXPERIMENTAL_OCI=1
      - run: |
          helm package ${{ inputs.path }}
          helm push ./${{inputs.name}}-${{inputs.version}}.tgz oci://ghcr.io/${{ github.repository }}

