name: 'Static Analysis'

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  static-analysis-run:
    name: 'Static Analysis (fmt, Clippy, Audit, Deny, Udeps, Outdated)'
    runs-on: arc-runner-set

    # Use an official slim image so the cache works exactly the same locally
    container:
      image: webgrip/rust-ci-runner:latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: "cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}"

      # ---------- rustfmt ----------
      - name: rustfmt check
        run: cargo fmt --all -- --check

      # ---------- Clippy (like PHPStan/Psalm) ----------
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        if: always()

      # ---------- Security CVE scan ----------
      - name: cargo audit
        run: cargo audit
        if: always()

      # ---------- Policy / licence / advisories ----------
      - name: cargo deny
        run: cargo deny --all-features check
        if: always()

      # ---------- Unused dependencies ----------
      - name: cargo udeps
        run: cargo +nightly udeps --all-targets
        if: always()

      # ---------- Outdated dependencies table ----------
      - name: cargo outdated
        run: cargo outdated --workspace --depth=1
        if: always()

      # ---------- Minimum-supported Rust version (nice-to-have) ----------
      - name: cargo msrv
        run: cargo msrv verify
        if: always()

      # ---------- Sort Cargo.toml files ----------
      - name: cargo sort
        run: cargo sort --workspace --check
        if: always()
