name: 'Static Analysis'

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  static-analysis-run:
    name: 'Static Analysis (fmt, Clippy, Audit, Deny, Udeps, Outdated)'
    runs-on: arc-runner-set

    container:
      image: webgrip/rust-ci-runner:latest

    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        include:
          - task: fmt
            cmd: cargo fmt --all -- --check

          - task: clippy
            cmd: cargo clippy --all-targets --all-features -- -D warnings

          - task: audit
            cmd: cargo audit

          - task: deny
            cmd: cargo deny --all-features check --hide-inclusion-graph

          - task: udeps
            cmd: cargo +nightly udeps --all-targets

          - task: outdated
            cmd: cargo outdated --workspace --depth=1

          - task: msrv
            cmd: cargo msrv verify

          - task: sort
            cmd: cargo sort --workspace --check
  
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: "cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}"

      - name: Run ${{ matrix.task }}
        run: ${{ matrix.cmd }}
