name: "[Workflow] Semantic Release (Rust + JS)"

on:
  workflow_call:
    inputs:
      release-type:
        description: "Explicit release level (major | minor | patch). Leave blank for auto‑detect."
        required: false
        type: string
    outputs:
      version:
        description: "Published version"
        value: ${{ jobs.semantic-release.outputs.version }}

permissions:              # Applies to all jobs unless overridden
  contents: write
  pull-requests: write
  issues: write
  statuses: write

concurrency:
  group: semantic-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-release:
    name: "Semantic Release"
    runs-on: arc-runner-set      # Use ubuntu-latest if you prefer GH‑hosted runners
    outputs:
      version: ${{ steps.out.outputs.version }}

    steps:
      - id: release
        uses: webgrip/workflows/.github/composite-actions/semantic-release@main
        with:
          release-type: ${{ inputs.release-type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Propagate version output
        id: out
        run: echo "version=${{ steps.release.outputs.version }}" >> "$GITHUB_OUTPUT"