name: "[Call] Bootstrap repository issues"

on:
  workflow_call:
    inputs:
      repo_name:
        description: "Name of the new repository"
        type: string
        required: true
    secrets:
      WEBGRIP_CI_CLIENT_ID:
        description: "GitHub App ID (numeric)"
        required: true
      WEBGRIP_CI_APP_PRIVATE_KEY:
        description: "GitHub App private key (PEM)"
        required: true

permissions:
  issues: write
  contents: write

jobs:
  bootstrap-issues:
    name: "Bootstrap repository issues from prompts"
    uses: ./.github/workflows/github-issues-create-by-prompt.yml
    with:
      prompt-repository: webgrip/agentic-workflows
      prompt-paths: '[".github/prompts/set-up-documentation.prompt.yml",".github/prompts/set-up-docker.prompt.yml",".github/prompts/set-up-helm.prompt.yml"]'
      issue-title: ${{ inputs.repo_name }}
      issue-repository: ${{ github.repository }}
    secrets:
      WEBGRIP_CI_CLIENT_ID: ${{ secrets.WEBGRIP_CI_CLIENT_ID }}
      WEBGRIP_CI_APP_PRIVATE_KEY: ${{ secrets.WEBGRIP_CI_APP_PRIVATE_KEY }}
