name: 'Tests'

on:
  workflow_call:

jobs:
  tests-run:
    name: '${{ matrix.testsuite }}'
    runs-on: ubuntu-latest
    container:
      image: php:8.2-cli
    strategy:
      fail-fast: false
      matrix:
        testsuite: [ 'Unit', 'Integration', 'Functional' ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: vendor
          key: "composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}"

      - name: 'Run ${{ matrix.testsuite }} tests'
        run: |
          case "${{ matrix.testsuite }}" in
            "Unit")
              ./vendor/bin/phpunit -c ./phpunit.xml.dist --testsuite unit --fail-on-risky --coverage-php coverage/unit.cov --coverage-html coverage/unit
              ;;
            "Integration")
              ./vendor/bin/phpunit -c ./phpunit.xml.dist --testsuite integration --fail-on-risky --exclude-group=db --coverage-php coverage/integration.cov --coverage-html coverage/integration
              ;;
            "Functional")
              ./vendor/bin/phpunit -c ./phpunit.xml.dist --testsuite functional --fail-on-risky --coverage-php coverage/functional.cov --coverage-html coverage/functional || true
              ;;
            *)
              echo "Unknown testsuite"
              exit 1
              ;;
          esac

      - name: 'Upload coverage artifact'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.testsuite }}
          path: coverage
          retention-days: 1
