name: "Update TechDocs"

on:
  workflow_call:
    inputs:
      source-dir:
        type: string
        description: 'The directory containing the techdocs files'
        required: false
        default: 'docs/techdocs'
      cname:
        type: string
        description: 'The custom domain for the TechDocs site'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-deps-generate-and-deploy:
    name: "Install dependencies, generate with mkdocs, upload artifact and deploy to GitHub Pages"
    runs-on: ubuntu-latest
    env:
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: download, validate, install plantuml and its dependencies
        run: |
          curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.4.jar/download
          echo "be498123d20eaea95a94b174d770ef94adfdca18  plantuml.jar" | sha1sum -c -
          mv plantuml.jar /opt/plantuml.jar
          mkdir -p "$HOME/.local/bin"
          echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> "$HOME/.local/bin/plantuml"
          chmod +x "$HOME/.local/bin/plantuml"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          sudo apt-get install -y graphviz

      - name: Install techdocs-cli and mermaid-cli
        run: |
          sudo npm install -g \
            @techdocs/cli@1.8.25 \
            @mermaid-js/mermaid-cli@11.4.2

      - name: Install mkdocs plugins
        run: |
          python -m pip install \
            mkdocs-techdocs-core==1.5.2 \
            markdown-inline-mermaid==1.0.4 \
            mkdocs-mermaid2-plugin==1.2.1 \
            mkdocs-macros-plugin==1.3.7

      - name: Generate docs site
        run: techdocs-cli generate --no-docker --verbose --source-dir ${{ inputs.source-dir }} --output-dir techdocs-site

      - name: Put in artifact
        uses: actions/upload-artifact@v4
        with:
          name: techdocs-site
          path: techdocs-site
          retention-days: 1

      - name: GitHub Pages Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./techdocs-site
          cname: ${{ inputs.cname }}